### ISSUE TITLE
Unable to create alignment view and plot for html file

### ISSUE THREAD

**Issue by asgarhussain** [pinetree1/crispr-dav#1]
I am getting following error while running run.sh 
Merging data and creating plots for del.
[!] I do not know how to interpret input './align/del_can.txt'
        [  499] BMS::TableReader::input
        [  517] main::read_source
        [   64] main
Failed to create canvasXpress alignment view
Align folder does not have any file of this name.

**Comment by pinetree1** [comment]
This issue was resolved since release tag v2.2.3. If you are using older version, please do a new pull. Let me know how it goes. Thank you.
